# Generated by Django 4.2 on 2026-04-03 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('total_time', models.PositiveIntegerField(default=0)),
                ('social_time', models.PositiveIntegerField(default=0)),
                ('study_time', models.PositiveIntegerField(default=0)),
                ('continuous_usage', models.PositiveIntegerField(default=0)),
                ('time_of_day', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default='evening', max_length=20)),
                ('apps_list', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('detected_state', models.CharField(choices=[('normal', 'Normal'), ('stressed', 'Stressed'), ('fatigued', 'Fatigued'), ('distracted', 'Distracted'), ('overuse', 'Overuse')], default='normal', max_length=20)),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('confidence', models.FloatField(default=0.5)),
                ('behavior_pattern', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='none', max_length=10)),
                ('action_type', models.CharField(choices=[('focus_mode', 'Focus Mode'), ('digital_detox', 'Digital Detox'), ('rest_mode', 'Rest Mode'), ('none', 'None')], default='none', max_length=20)),
                ('action_description', models.TextField(blank=True)),
                ('action_duration', models.CharField(blank=True, max_length=50)),
                ('system_changes', models.JSONField(default=list)),
                ('user_message', models.TextField(blank=True)),
                ('parent_alert', models.CharField(choices=[('none', 'None'), ('consider', 'Consider'), ('required', 'Required')], default='none', max_length=10)),
                ('raw_result', models.JSONField(default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='screen_monitor.screensession')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
