# Generated by Django 4.2 on 2026-04-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appusage',
            name='unique_app_usage_per_day',
        ),
        migrations.AlterUniqueTogether(
            name='appusage',
            unique_together={('device', 'package_name', 'date')},
        ),
    ]
