# Generated by Django 4.2 on 2026-04-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_google_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('teen', 'Teen'), ('mentor', 'Mentor'), ('admin', 'Admin')], max_length=10),
        ),
    ]
