# Generated by Django 4.2 on 2026-04-09 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0006_alter_child_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_action', models.JSONField()),
                ('action_taken', models.CharField(blank=True, max_length=50)),
                ('outcome', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10, null=True)),
                ('mode_before', models.CharField(max_length=20)),
                ('mode_after', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentActionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.BooleanField(default=False)),
                ('outcome_rating', models.IntegerField(blank=True, null=True)),
                ('corrective_tip_given', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child')),
                ('interaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relationship_intelligence.interactionlog')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('low', 'Low'), ('stressed', 'Stressed')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='children.child')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_checkins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('response_delay', 'Response Delay'), ('skipped_interaction', 'Skipped Interaction'), ('app_usage', 'App Usage'), ('negative_feedback', 'Negative Feedback')], max_length=20)),
                ('value', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_signals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_score', models.IntegerField(default=50)),
                ('engagement_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('current_mode', models.CharField(choices=[('normal', 'Normal'), ('trust_rebuilding', 'Trust Rebuilding'), ('resistance_handling', 'Resistance Handling')], default='normal', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('engagement_history', models.JSONField(default=list)),
                ('trust_history', models.JSONField(default=list)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_states', to='children.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_parent_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
