# backend/apps/relationship_intelligence/migrations/0002_relationshipanalysis.py

# Generated by Django 4.2 on 2026-04-09 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_alter_child_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relationship_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_input', models.JSONField()),
                ('child_input', models.JSONField()),
                ('analysis_result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_analyses', to='children.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]