# Generated by Django 4.2 on 2026-04-18 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('children', '0006_alter_child_stage'),
        ('relationship_intelligence', '0002_relationshipanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicFixHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(blank=True)),
                ('behavior', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('context', models.TextField(blank=True)),
                ('fix_result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_fixes', to='children.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_fixes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
