# Generated by Django 4.2 on 2026-04-29 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField(default=10, help_text='Duration in minutes (2–20)')),
                ('suggested_time', models.TimeField(blank=True, null=True)),
                ('repetition', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('created_by', models.CharField(choices=[('parent', 'Parent'), ('teen', 'Teen')], max_length=10)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modified', 'Modified')], default='approved', max_length=10)),
                ('teen_feedback', models.TextField(blank=True, default='')),
                ('adjusted_task', models.CharField(blank=True, default='', help_text='Modified task title suggested after review', max_length=255)),
                ('ai_feasibility', models.CharField(blank=True, default='', max_length=50)),
                ('ai_suggestion', models.TextField(blank=True, default='')),
                ('stage', models.CharField(choices=[('not_started', 'Not Started'), ('building', 'Building'), ('formed', 'Formed')], default='not_started', max_length=15)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('total_completions', models.PositiveIntegerField(default=0)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_habits', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='The parent who created/monitors this habit (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_habits', to=settings.AUTH_USER_MODEL)),
                ('teen', models.ForeignKey(help_text='The teen this habit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='teen_habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('instant', 'Instant'), ('streak', 'Streak Bonus'), ('milestone', 'Milestone')], max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('points', models.PositiveIntegerField(default=0)),
                ('badge_emoji', models.CharField(blank=True, default='', max_length=10)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='habit_builder.habit')),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateField(auto_now_add=True, help_text='Date only, for streak tracking')),
                ('checked_by', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habit_builder.habit')),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('habit', 'completed_date')},
            },
        ),
    ]
