# Generated by Django 4.2 on 2026-04-17 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('children', '0006_alter_child_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyChildhoodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('speech_status', models.CharField(blank=True, max_length=255)),
                ('response_name', models.CharField(blank=True, max_length=255)),
                ('eye_contact', models.CharField(blank=True, max_length=255)),
                ('motor_skills', models.CharField(blank=True, max_length=255)),
                ('social_behavior', models.CharField(blank=True, max_length=255)),
                ('eating_habit', models.CharField(blank=True, max_length=255)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('screen_time', models.FloatField(blank=True, null=True)),
                ('problem_selected', models.CharField(blank=True, max_length=255)),
                ('parent_text', models.TextField(blank=True, null=True)),
                ('input_confidence', models.CharField(blank=True, max_length=50)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_childhood_reports', to='children.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
