# Generated by Django 4.2 on 2026-04-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_childhood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlychildhoodreport',
            name='behavior_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earlychildhoodreport',
            name='emotional_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earlychildhoodreport',
            name='routine_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earlychildhoodreport',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
