import React from 'react';
import { motion } from 'framer-motion';
import { FiTrendingUp, FiTarget, FiAlertCircle, FiHeart, FiAward } from 'react-icons/fi';

const TeenBehaviorInsights = ({ analysis }) => {
    if (!analysis) return null;

    const riskColor = analysis.risk_level === 'HIGH' ? 'text-rose-500' : 'text-amber-400';
    const riskBg = analysis.risk_level === 'HIGH' ? 'bg-rose-500/10' : 'bg-amber-400/10';

    return (
        <div className="space-y-6">
            {/* CORE SCORES PANEL */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                <div className="lg:col-span-8 p-10 bg-white/5 border border-white/10 rounded-[3rem] shadow-2xl relative overflow-hidden">
                    <div className="relative z-10">
                        <div className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-4 opacity-50">Operational Summary</div>
                        <h3 className="text-2xl font-bold text-white mb-4 leading-tight max-w-lg">{analysis.summary}</h3>
                        
                        <div className="flex flex-wrap gap-2 mt-6">
                            {analysis.behavior_patterns.map((p, i) => (
                                <span key={i} className="px-4 py-2 bg-indigo-500/20 text-indigo-300 rounded-xl text-xs font-bold flex items-center gap-2 border border-indigo-500/30">
                                    <FiTrendingUp /> {p}
                                </span>
                            ))}
                        </div>
                    </div>
                </div>

                <div className={`lg:col-span-4 p-8 ${riskBg} border border-white/5 rounded-[3rem] flex flex-col items-center justify-center text-center`}>
                    <div className="text-6xl font-black mb-1 text-white tracking-tighter">{analysis.risk_score}</div>
                    <div className={`font-black uppercase tracking-widest text-sm ${riskColor}`}>Aggregate Risk Level</div>
                    <p className="mt-4 text-xs font-medium text-slate-400 max-w-[200px]">Risk analysis generated by cross-referencing App-Types vs Peak Activity Hours</p>
                </div>
            </div>

            {/* ACTIONABLE PANELS */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mt-12">
                <section>
                    <h3 className="flex items-center gap-2 text-indigo-400 font-bold uppercase tracking-[0.2em] text-xs mb-6 px-2">
                        <FiTarget /> Parent Action Protocols
                    </h3>
                    <div className="space-y-4">
                        {analysis.parent_advice.map((advice, i) => (
                            <motion.div initial={{ x: -20, opacity: 0 }} whileInView={{ x: 0, opacity: 1 }} key={i} className="bg-white/5 p-6 rounded-3xl border border-white/5 flex gap-4">
                                <span className="w-8 h-8 rounded-full bg-indigo-500 flex-shrink-0 flex items-center justify-center text-white font-bold text-xs shadow-lg">{i+1}</span>
                                <p className="text-slate-200 text-sm font-semibold leading-relaxed">{advice}</p>
                            </motion.div>
                        ))}
                    </div>
                </section>

                <section>
                    <h3 className="flex items-center gap-2 text-pink-400 font-bold uppercase tracking-[0.2em] text-xs mb-6 px-2">
                        <FiAward /> Improvement Roadmap
                    </h3>
                    <div className="space-y-4">
                        {analysis.improvement_plan.map((step, i) => (
                            <motion.div initial={{ x: 20, opacity: 0 }} whileInView={{ x: 0, opacity: 1 }} key={i} className="bg-white/5 p-6 rounded-3xl border border-pink-500/10 flex gap-4 border-l-4 border-l-pink-500/50">
                                <span className="text-xl">🏆</span>
                                <p className="text-slate-200 text-sm font-semibold leading-relaxed">{step}</p>
                            </motion.div>
                        ))}
                    </div>
                </section>
            </div>
            
            {/* FOOTER RISKS */}
            <div className="p-8 bg-white/5 rounded-3xl border border-red-500/10 border-t-red-500/50">
                <div className="flex items-center gap-3 mb-4">
                   <FiAlertCircle className="text-red-500 text-2xl" />
                   <h4 className="text-white font-black text-lg uppercase tracking-tight">Vulnerability Report</h4>
                </div>
                <ul className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-4">
                    {analysis.risk_reasons.map((r, i) => (
                        <li key={i} className="flex items-start gap-3 text-sm text-slate-400">
                            <span className="text-red-500/50 mt-1">•</span> {r}
                        </li>
                    ))}
                </ul>
            </div>
        </div>
    );
};

export default TeenBehaviorInsights;