# Generated by Django 4.2 on 2026-03-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10),
        ),
    ]
