# Generated by Django 4.2 on 2026-04-08 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('children', '0006_alter_child_stage'),
        ('assessments', '0004_assessment_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDiscoveryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_labels', models.JSONField(default=list)),
                ('scores', models.JSONField(default=dict)),
                ('best_career_title', models.CharField(max_length=200)),
                ('best_career_emoji', models.CharField(blank=True, max_length=10)),
                ('best_career_why', models.TextField(blank=True)),
                ('alternatives', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='children.child')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
