# Generated by Django 4.2 on 2026-04-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_careerdiscoveryresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerdiscoveryresult',
            name='task',
            field=models.TextField(blank=True),
        ),
    ]
