# Generated by Django 4.2 on 2026-03-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='child_avatars/')),
                ('stage', models.CharField(choices=[('pregnancy', 'Pregnancy'), ('early_childhood', 'Early Childhood (0-3)'), ('growing_stage', 'Growing Stage (4-8)'), ('teen_age', 'Teen Age (9+)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
