# Generated by Django 4.2 on 2026-03-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='stage',
            field=models.CharField(choices=[('pregnancy', 'Pregnancy'), ('early_childhood', 'Early Childhood (0-5)'), ('growing_stage', 'Growing (6-12)'), ('teen_age', 'Teen (13-20)')], max_length=20),
        ),
    ]
