# Generated by Django 4.2 on 2026-03-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_alter_child_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
