# Generated by Django 4.2 on 2026-04-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_alter_child_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
