# Generated by Django 4.2 on 2026-04-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0007_child_firebase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
