# Generated by Django 4.2 on 2026-04-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytask',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]